//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preference
    {
        public int id { get; set; }
        public int degree { get; set; }
        public int user { get; set; }
    
        public virtual Degree Degree1 { get; set; }
        public virtual User User1 { get; set; }
    }
}
