//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversityDegreeFee
    {
        public int id { get; set; }
        public decimal annualFee { get; set; }
    
        public virtual UniversityDegree UniversityDegree { get; set; }
    }
}
