//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class MajorInterest
    {
        public int id { get; set; }
        public int interest { get; set; }
        public int major { get; set; }
        public int rating { get; set; }
    
        public virtual Interest Interest1 { get; set; }
        public virtual Major Major1 { get; set; }
    }
}
