//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserHobby
    {
        public int id { get; set; }
        public int hobby { get; set; }
        public int user { get; set; }
    
        public virtual Hobby Hobby1 { get; set; }
        public virtual User User1 { get; set; }
    }
}
