#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FutureRecommenderApp.Resource", IsApplication=true)]

namespace FutureRecommenderApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int my_blue = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int my_gray = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int my_green = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int my_purple = 2130968578;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Bachelor = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int logout = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int university = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070007
			public const int AddSkill = 2131165191;
			
			// aapt resource value: 0x7f070032
			public const int Thumbnail = 2131165234;
			
			// aapt resource value: 0x7f070001
			public const int _add_ = 2131165185;
			
			// aapt resource value: 0x7f070012
			public const int _budget = 2131165202;
			
			// aapt resource value: 0x7f07002a
			public const int _city = 2131165226;
			
			// aapt resource value: 0x7f070027
			public const int _email = 2131165223;
			
			// aapt resource value: 0x7f07000c
			public const int _fname = 2131165196;
			
			// aapt resource value: 0x7f07001a
			public const int _hobbylist = 2131165210;
			
			// aapt resource value: 0x7f070022
			public const int _interestlist = 2131165218;
			
			// aapt resource value: 0x7f07000f
			public const int _lname = 2131165199;
			
			// aapt resource value: 0x7f070028
			public const int _name = 2131165224;
			
			// aapt resource value: 0x7f070000
			public const int _name_ = 2131165184;
			
			// aapt resource value: 0x7f07002c
			public const int _qualification = 2131165228;
			
			// aapt resource value: 0x7f070005
			public const int _rating_ = 2131165189;
			
			// aapt resource value: 0x7f07001e
			public const int _skilllist = 2131165214;
			
			// aapt resource value: 0x7f07002d
			public const int addHobby = 2131165229;
			
			// aapt resource value: 0x7f07002f
			public const int addInterest = 2131165231;
			
			// aapt resource value: 0x7f07002e
			public const int addSkill = 2131165230;
			
			// aapt resource value: 0x7f070010
			public const int budget = 2131165200;
			
			// aapt resource value: 0x7f070019
			public const int button1 = 2131165209;
			
			// aapt resource value: 0x7f07001d
			public const int button2 = 2131165213;
			
			// aapt resource value: 0x7f070021
			public const int button3 = 2131165217;
			
			// aapt resource value: 0x7f070023
			public const int button4 = 2131165219;
			
			// aapt resource value: 0x7f070015
			public const int city = 2131165205;
			
			// aapt resource value: 0x7f070034
			public const int degree = 2131165236;
			
			// aapt resource value: 0x7f070025
			public const int editText1 = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int editText2 = 2131165222;
			
			// aapt resource value: 0x7f070036
			public const int editText3 = 2131165238;
			
			// aapt resource value: 0x7f070037
			public const int editText4 = 2131165239;
			
			// aapt resource value: 0x7f070038
			public const int editText5 = 2131165240;
			
			// aapt resource value: 0x7f070039
			public const int editText6 = 2131165241;
			
			// aapt resource value: 0x7f07000b
			public const int email = 2131165195;
			
			// aapt resource value: 0x7f070030
			public const int goToEditProfile = 2131165232;
			
			// aapt resource value: 0x7f070017
			public const int hobby = 2131165207;
			
			// aapt resource value: 0x7f070024
			public const int imageView1 = 2131165220;
			
			// aapt resource value: 0x7f07001f
			public const int interest = 2131165215;
			
			// aapt resource value: 0x7f070002
			public const int linearLayout1 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int linearLayout2 = 2131165187;
			
			// aapt resource value: 0x7f070031
			public const int listView1 = 2131165233;
			
			// aapt resource value: 0x7f07000d
			public const int name = 2131165197;
			
			// aapt resource value: 0x7f070013
			public const int qualification = 2131165203;
			
			// aapt resource value: 0x7f070035
			public const int rating = 2131165237;
			
			// aapt resource value: 0x7f07000a
			public const int scrollView1 = 2131165194;
			
			// aapt resource value: 0x7f07001b
			public const int skill = 2131165211;
			
			// aapt resource value: 0x7f070009
			public const int skillRatingSpinner = 2131165193;
			
			// aapt resource value: 0x7f070006
			public const int skillspinner = 2131165190;
			
			// aapt resource value: 0x7f070016
			public const int spinner1 = 2131165206;
			
			// aapt resource value: 0x7f070014
			public const int spinner2 = 2131165204;
			
			// aapt resource value: 0x7f070004
			public const int textView1 = 2131165188;
			
			// aapt resource value: 0x7f070018
			public const int textView11 = 2131165208;
			
			// aapt resource value: 0x7f07001c
			public const int textView13 = 2131165212;
			
			// aapt resource value: 0x7f070020
			public const int textView15 = 2131165216;
			
			// aapt resource value: 0x7f070008
			public const int textView2 = 2131165192;
			
			// aapt resource value: 0x7f07000e
			public const int textView3 = 2131165198;
			
			// aapt resource value: 0x7f070029
			public const int textView5 = 2131165225;
			
			// aapt resource value: 0x7f070011
			public const int textView7 = 2131165201;
			
			// aapt resource value: 0x7f07003a
			public const int toolbar = 2131165242;
			
			// aapt resource value: 0x7f070033
			public const int university = 2131165235;
			
			// aapt resource value: 0x7f07002b
			public const int xya = 2131165227;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Add_Hobby_List_Item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Add_Skill_Interest_List_Item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int addHobby = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int addInterest = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int addSkill = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dashboard = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int deleteHobby = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int deleteInterest = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int deleteSkill = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int EditProfile = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Main = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Profile = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Recommendation = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int RecommendationItem = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int signup = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Toolbar = 2130903055;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyCustomTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int MyTheme = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
