//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreLevel
    {
        public int id { get; set; }
        public int preLevel1 { get; set; }
    
        public virtual PreDegree PreDegree { get; set; }
    }
}
