//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recommendation
    {
        public int id { get; set; }
        public int user { get; set; }
        public Nullable<int> major { get; set; }
    
        public virtual Major Major1 { get; set; }
        public virtual User User1 { get; set; }
    }
}
