//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int location { get; set; }
        public int qualification { get; set; }
        public decimal percentage { get; set; }
        public decimal annualBudget { get; set; }
    
        public virtual Location Location1 { get; set; }
        public virtual PreDegree PreDegree { get; set; }
        public virtual User User { get; set; }
    }
}
